# Generated by Django 4.2.20 on 2025-04-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('infos', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='BookAndTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBook.book')),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionBook.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BookAndAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionBook.author')),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBook.book')),
            ],
        ),
    ]
